### ISSUE TITLE
Mostrar alerta en listado vacio

### ISSUE THREAD

**Issue by shinlucho** [cecig87/PruebaInfoC#1]
Cuando no se han cargado paises, actualmente no se muestra nada ni bien se ingresa a la aplicacion, y cuando se va a la pagina /list muestra una tabla vacia. Deberia de mostrarse algun mensaje que diga que todavia no se ha cargado ningun pais.

Podria hacerse con [alerts](https://getbootstrap.com/docs/4.5/components/alerts/) o con [jumbotron](https://getbootstrap.com/docs/4.5/components/jumbotron/).

**Comment by cecig87** [comment]
Sí, lo había notado, pero todavía no lo había hecho. Ahora voy a ver qué es jumbotron.

**Comment by cecig87** [comment]
Implementado.
