### ISSUE TITLE
Advertencia al eliminar pais

### ISSUE THREAD

**Issue by shinlucho** [cecig87/PruebaInfoC#2]
Antes de eliminar un pais, deberia mostrarse un [modal](https://getbootstrap.com/docs/4.5/components/modal/) para confirmar si realmente quiere eliminar el pais. Esto se suele usar para evitar que el usuario borre cosas al presionar un boton sin querer.

**Comment by cecig87** [comment]
También había pensado en poner una advertencia. Ahora voy a ver cómo se usa un modal.

**Comment by cecig87** [comment]
Implementado.
