### ISSUE TITLE
Organizar botones en tabla

### ISSUE THREAD

**Issue by shinlucho** [cecig87/PruebaInfoC#4]
En lugar de tener una columna para cada accion, se podria juntar todos los botones en una sola columna para ahorrar espacio, algo similar a esto:

![acciones](https://i.vgy.me/YmViOs.png)

Tambien se podria usar [Font Awesome](https://fontawesome.com/) para mostrar iconos en lugar de texto en los botones.

**Comment by cecig87** [comment]
Implementado.
